name: Sync Hugging Face Space to GitHub

on:
  schedule:
    - cron: '0 0 * * 1'  # 每週一 00:00 UTC
  workflow_dispatch:     # 允許手動執行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v3

      - name: Clone Hugging Face Space
        run: |
          git clone --depth=1 https://huggingface.co/spaces/aomou/DwCleaner hf_space

      - name: Sync files from HF Space
        run: |
          for i in {1..5}; do
            rsync -av --delete hf_space/ ./ && break || sleep 10;
          done
          rm -rf hf_space

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-sync from Hugging Face" || echo "No changes to commit"
          git push
